name: Test Meta Output

on:
  workflow_dispatch:
    inputs:
      repo_owner:
        required: true
        type: string
        description: Repo Owner
      app_name:
        required: true
        type: string
        description: App Name

jobs:
  bake:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2.4.0
      -  
        name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v3.6.2
        with:
          images: |
            ${{ inputs.repo_owner }}/${{ inputs.app_name }}
            ghcr.io/${{ inputs.repo_owner }}/${{ inputs.app_name }}
          labels: |
            org.opencontainers.image.title=${{ inputs.app_name }}
            org.opencontainers.image.description=${{ inputs.app_name }}
            org.opencontainers.image.vendor=${{ inputs.repo_owner }}
      - 
        name: Get Meta Output
        id: get_meta
        run: |
          echo ${{ fromJSON(steps.docker_meta.outputs.json).tags[0] }}
          echo ${{ fromJSON(steps.docker_meta.outputs.json).tags[1] }}
          echo ${{ fromJSON(steps.docker_meta.outputs.json).tags[2] }}